import React, { useState } from 'react'
import ButtonPrimary from '../../../../Elements/Buttons/ButtonPrimary'
import FormInput from '../../../../Elements/Form/FormInput'

const ConfirmAuthAppModal = ({}) => {

    const [formData, setFormData] = useState({
        digit1:'',
        digit2:'',
        digit3:'',
        digit4:'',
        digit5:'',
        digit6:'',
        email:'',
        password:''
      })

      var otp_boxes = document.querySelectorAll('.otp-digits')
    otp_boxes.forEach((otp_box, index) => {
        otp_box.dataset.id = index
        let box_len = otp_boxes.length
        box_len = box_len - 1
        otp_box.addEventListener('keyup', (e)=>{
            if (e.target.value.length > 1) {
                e.target.value = e.target.value.slice(0,1); // prevent further input if length > 1
              }
            if(index < box_len){
                    if (otp_box.value.length == 1){
                        otp_boxes[parseInt(index) + 1].focus()
                    }
                }
            if(index > 0){
                    if (otp_box.value.length == 0){
                        otp_boxes[parseInt(index) - 1].focus()
                    }
                }
            })
    });
      
    
    const handleChange = (e) => {
        setFormData({...formData, [e.target.name]:e.target.value})
    }
    const handleSubmit = (e) => {
    e.preventDefault()
    console.log(formData)
    }



  return (
    <div className='bg-white m-auto rounded-ten py-8 px-5 relative md:py-8 md:px-8 lg:px-14 z-50 w-ninetyFivePercent sm:w-sixtyFivePercent md:w-sixtyPercent lg:w-fiftyPercent max-w-lg h-fit'>
            <div className='text-center'>
                <h4 className='text-2xl md:text-3xl pb-1 text-brandGray14x font-avenirHeavy'>Set authenticator app</h4>
                <form action="" method='post' onSubmit={handleSubmit} className='flex flex-col gap-5 py-7'>
                    <p className='text-center'>Please enter the 6 digit OTP generated by the authentication app</p>   
                    <div className='border-b-0.5 border-b-brandGray2x'>
                        <div className="grid grid-cols-12  pt-5 gap-2 pb-4 lg:pb-8 sm:gap-4 xs:flex xs:flex-wrap xs:justify-around xs:gap-2">
                            <input type="number" id="digit1" maxlength="1" required onChange={handleChange} name="digit1" data-next="digit2" className="otp-digits bg-transparent border border-brandGray22x col-span-2 hover:border-brandBlue1x hover:border-1 focus:border-brandBlue1x focus:ring-2 border-1 focus:outline-none rounded-ten w-11 h-11 sm:w-12 sm:h-12 lg:w-16 lg:h-16 xl:text-2xl text-center" />
                            <input type="number" id="digit2" maxlength="1" required onChange={handleChange} name="digit2" data-next="digit3" data-previous="digit1" className="otp-digits bg-transparent border border-brandGray22x col-span-2 hover:border-brandBlue1x hover:border-1 focus:border-brandBlue1x focus:ring-2 border-1 focus:outline-none rounded-ten  w-11 h-11 sm:w-12 sm:h-12 lg:w-16 lg:h-16  xl:text-2xl text-center" />
                            <input type="number" id="digit3" maxlength="1" required onChange={handleChange} name="digit3" data-next="digit4" data-previous="digit2" className="otp-digits bg-transparent border border-brandGray22x col-span-2 hover:border-brandBlue1x hover:border-1 focus:border-brandBlue1x focus:ring-2 border-1 focus:outline-none rounded-ten  w-11 h-11 sm:w-12 sm:h-12 lg:w-16 lg:h-16  xl:text-2xl text-center"/>
                            <div className="hidden xs:block xs:w-full bg-transparent h-0"></div>
                            <input type="number" id="digit4" maxlength="1" required onChange={handleChange} name="digit4" data-next="digit5" data-previous="digit3" className="otp-digits bg-transparent border border-brandGray22x col-span-2 hover:border-brandBlue1x hover:border-1 focus:border-brandBlue1x focus:ring-2 border-1 focus:outline-none rounded-ten  w-11 h-11 sm:w-12 sm:h-12 lg:w-16 lg:h-16  xl:text-2xl text-center"/>
                            <input type="number" id="digit5" maxlength="1" required onChange={handleChange} name="digit5" data-next="digit6" data-previous="digit4" className="otp-digits bg-transparent border border-brandGray22x col-span-2 hover:border-brandBlue1x hover:border-1 focus:border-brandBlue1x focus:ring-2 border-1 focus:outline-none rounded-ten  w-11 h-11 sm:w-12 sm:h-12 lg:w-16 lg:h-16  xl:text-2xl text-center"/>
                            <input type="number" id="digit6" maxlength="1" required onChange={handleChange} name="digit6" data-previous="digit5" className="otp-digits bg-transparent border border-brandGray22x col-span-2 hover:border-brandBlue1x hover:border-1 focus:border-brandBlue1x focus:ring-2 border-1 focus:outline-none rounded-ten  w-11 h-11 sm:w-12 sm:h-12 lg:w-16 lg:h-16  xl:text-2xl text-center"/>
                        </div>
                    </div>
                   
                   <FormInput handleChange={handleChange} labelFont={'font-avenirMedium text-left'} inputType={'email'} labelColor={'text-black'} inputName={'email'} inputId={'email'} inputPlaceholder={' '} inputLabel={'Enter Email Address'} />
                   <FormInput handleChange={handleChange} labelFont={'font-avenirMedium text-left'} labelColor={'text-black'} inputName={'password'} inputId={'password'} inputType={'password'} inputPlaceholder={' '} inputLabel={'Confirm password'} />
                    <div className="col-span-1 mds:col-span-2 sm:col-span-2 pt-5 flex items-center justify-center">
                        <ButtonPrimary text={'Verify email address'} type={'submit'} />
                    </div>
                </form>
            </div>
        </div>
  )
}

export default ConfirmAuthAppModal