version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Pandascrow-v2-Webapp
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_npm_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
